version: '3.8'

services:
  web:
    container_name: web
    build: frontend
    image: deepanshurawat6/web_frontend:0.2.0
    networks:
      - object-detection-private
      - object-detection-public
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - yolo5

  yolo5:
    container_name: yolo5
    build: yolo5
    networks:
      - object-detection-private
    image: deepanshurawat6/detection-model:0.0.6
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - "8081:8081"

  mongodb:
    container_name: mongodb
    image: mongo:latest

    networks:
      - object-detection-private
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - ./mongo/data:/data/db

  polybot:
    container_name: polybot
    image: deepanshurawat6/polybot:0.0.3
    networks:
      - object-detection-private
      - object-detection-public
    depends_on:
      - yolo5


volumes:
  mongodb:
    driver: local

networks:
  object-detection-public:
    name: object-detection-public
    driver: bridge

  object-detection-private:
    name: object-detection-private
    driver: bridge