apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
spec:
  selector:
    matchLabels:
      app: polybot
  replicas: 1
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
        - name: polybot
          image: <URL>
          resources:
            requests:
              cpu: 500m
            limits:
              cpu: 1000m
          volumeMounts:
            - name: .telegramToken
              mountPath: /app/.telegramToken
              readOnly: true
              subPath: token
    volumes:
       - name: .telegramToken
         secret:
           secretName: .telegramToken

---
apiVersion: v1
kind: Secret
metadata:
  name: polybot-creds
data:
  username: am9obg==
  password: Mzk1MjgkdmRnN0pi
