apiVersion: v1
kind: Secret
metadata:
  name: polybot-creds
data:
  token: NjA4NzU2MDgwMTpBQUZHdWFSekFMU3B3TmhNLVZTTjdmZHlOVzNvZURKdWstMA==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
spec:
  selector:
    matchLabels:
      app: polybot
  replicas: 1
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
        - name: polybot
          image: 854171615125.dkr.ecr.us-east-1.amazonaws.com/deepanshurawat6-polybot:0.1.0
          resources:
            requests:
              cpu: 500m
              memory: 0.5Gi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: telegramtoken
              mountPath: /app/.telegramToken
              readOnly: true
              subPath: token
      volumes:
        - name: telegramtoken
          secret:
            secretName: polybot-creds
